### ISSUE TITLE
minified source breaks in Firefox 36

### ISSUE THREAD

**Issue by fozcode** [krampstudio/aja.js#13]
OK I'm not entirely sure what's wrong with the minified source, but using it like so:
`aja().method('post').url('/my/url').type('json').data(values)` where values is a POJO, on the server side I receive all of `values` munged into one argument, joined together with `=` and `\r\n`.  Internally it would seem that `isUrlEncoded` is ending up as `false` instead of `true`.
If I use the un-minified source, everything works correctly. So for my use case I have re-minified the source with YUI Compressor and then it all works fine.

**Comment by krampstudio** [comment]
My bad!!! I've published the last version without minifying the sources... so they were not in sync. Sorry error stands between the chair and the keyboard...

**Comment by krampstudio** [comment]
Could you try with the min file of 0.3.4 just published

**Comment by fozcode** [comment]
Yes that’s fixed it, many thanks.

Great library by the way!

Matt

**Comment by krampstudio** [comment]
cool thkx
