### ISSUE TITLE
grunt test failes

### ISSUE THREAD

**Issue by violacase** [krampstudio/aja.js#23]
On Windows10 machine with latest node and npm running 'grunt test' gives a lot of errors when executing "eslint:dist" (eslint) task

path\to\aja.js\src\aja.js

First line:
  1:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
etc....

**Comment by krampstudio** [comment]
Humm, the source code is encoded using LF. 
Just to be sure, what's your git configuration for line breaks?

**Comment by violacase** [comment]
I'm not familiar with git environment...

Google search gave me this: https://help.github.com/articles/dealing-with-line-endings/
I tried all the suggestions on that page but no luck...

**Comment by krampstudio** [comment]
Could you give me the result of `git config --get-all core.autocrlf`

**Comment by violacase** [comment]
Thanks for your attention. I suppose the problem is not fundamentally related with your project...
This is what i get:

λ git config --get-all core.autocrlf 
true
true

**Comment by krampstudio** [comment]
I have published a `.gitattributes` files that should normalize line ending on checkout. Could you try to checkout the repo again and run the tests?

**Comment by violacase** [comment]
Same error list

**Comment by krampstudio** [comment]
No, I want my sources having unix line breaks, for consistency reasons. The problem here comes from git on windows that converts line breaks when you checkout. 
You might just need to `git config --set auto-crlf false` on the project or globally.

**Comment by violacase** [comment]
Unfortunately my git env doesn't recognize the --set option. No problem for me though. I managed to do the work that had to be done.
Again, thanks for your attention and keep up the good work!
