### ISSUE TITLE
Wildcard in handler doesn't work

### ISSUE THREAD

**Issue by whatda** [krampstudio/aja.js#28]
Hi,

The wildcard for error code handlers doesn't seem to work:

```js
.on('success', cb)
.on('40*', function () {
    console.log('in 400 handler');
})
```

My code in this case is 403 and if I specify it explicitly, the handler gets called. But not with the `40*`.

**Comment by krampstudio** [comment]
The documentation was wrong, could you try by changing the wildcard by a `x`

**Comment by whatda** [comment]
Works like a charm, thx!

**Comment by krampstudio** [comment]
Cool, I might also need to support `*`. It seems more obvious...

**Comment by whatda** [comment]
Yeah, but I personally don't think it's necessary as long as "x" is documented. :)

**Comment by ultamatt** [comment]
Bump. I also struggled with this for an hour or two before finding this. I'll update your documentation if you'll merge my pull.

*Edit: 
Actually, you should change it here: The Readme looks fine. 
http://krampstudio.com/aja.js/#samples

**Comment by krampstudio** [comment]
@ultamatt thanks to report it. I've fixed the samples.
