### ISSUE TITLE
Support commonjs (browserify)

### ISSUE THREAD

**Issue by ramjoshi** [krampstudio/aja.js#3]
Currently the library cannot be used in common-js like environments or projects using browserify.

**Comment by krampstudio** [comment]
Ho, yes. I forgot the `main` in the package.json

**Comment by krampstudio** [comment]
0.2.1 should fix the issue

**Comment by ramjoshi** [comment]
Thanks! That works.

**Comment by krampstudio** [comment]
Just for the archive. You can use browserify with a module that doesn't use the `main` property. When you include such library, you can target the files to load by using the property `browser` of into your `package.json`.
