### ISSUE TITLE
Cannot make it work as RequireJS module

### ISSUE THREAD

**Issue by WhereJuly** [krampstudio/aja.js#37]
Hello! Thanks a lot for great functionality :)

I cannot make it work with RequireJS though. It just does not define the module.

I configure it like this
``` javascript
require.config({
    paths: {
        'myaja': '../../src/z_external/scripts/ajaJS/aja'
    }
});
```
I define and call it like this:
``` javascript
define(['myaja'], function(myaja) {
        var requirejs_aja = myaja; // here should be the reference to the module
        var global_aja = aja; // here expected the global instance
});
``` 
Here is what I get in the debugger:
``` javascript
  // this is Chrome dev tools debugger screen output
   var requirejs_aja = myaja; requirejs_aja = undefined // aja could not be defined as RequireJS module 
   var global_aja = aja; global_aja = aja() // Global aja is OK
```
There is no error from RequireJS and the module itself appears in my JS bundle but not being available as RequireJS module, just as global aja(). Can you check please what is wrong? Thank you.

**Comment by krampstudio** [comment]
Did you try  with the [minified version of aja](https://github.com/krampstudio/aja.js/blob/master/aja.min.js)?

```js
define(['path/to/aja.min'], function(aja){
 });
```

**Comment by WhereJuly** [comment]
I have just done. It works with the minified one. Thanks for the hint:))
