### ISSUE TITLE
Request Object not available from response

### ISSUE THREAD

**Issue by tremendus** [krampstudio/aja.js#39]
Hi, great library, my favorite Ajax lib actually ... 

I see from the docs and the source that there is no obvious way to get to the request object from the response. In my case, I would like to have an emitter called in the on('end') callback that emits the url, status code and the method for logging purposes. But doesn't seem currently possible. 

Happy to do a PR - where do you suggest to do this in source?

**Comment by krampstudio** [comment]
Glad you like it!
The simplest would be to add the `request` object as last parameter of all those `trigger` calls [here](https://github.com/krampstudio/aja.js/blob/master/src/aja.js#L523)

That's not the most elegant way but it should work and won't break compatibility.

If you have time to create a PR, that would be awesome.
