### ISSUE TITLE
There is a way to check progress on request?

### ISSUE THREAD

**Issue by reinaldorauch** [krampstudio/aja.js#40]
Looked at the docs and didn't saw anything straightforward to do it.

Any event like `.on('progress', () => {})` or something like that?

**Comment by krampstudio** [comment]
Yes there's a `progress` event, see https://github.com/krampstudio/aja.js/blob/master/src/aja.js#L504. Now that the support is good I should document it.

**Comment by reinaldorauch** [comment]
Will check it, thanks for the answer

**Comment by krampstudio** [comment]
Please reopen in case of issue
