### ISSUE TITLE
i got some error with post method

### ISSUE THREAD

**Issue by smildlzj** [krampstudio/aja.js#7]
https://github.com/krampstudio/aja.js/blob/master/src/aja.js#L450

Hi,
when i use the post method,i got something error,like this

```
 aja()
 .method('POST')
 .url('xxx')
 .data({__cms_uid: 1 , __cms_product: "test"})
 .go();
```

Chrome post like this:
![2015-01-19_190909](https://cloud.githubusercontent.com/assets/1638850/5799562/acb64716-a00e-11e4-8fe9-b78923f37792.png)

and the server got ` __cms_product` value : "test
__cms_uid=1"

so i review the source code,line450,params join by "`\n\r`" , is it ok?

i change it to "`&`" , error gone;

by the way,
suggest params value append this `encodeURIComponent`

**Comment by krampstudio** [comment]
Ho, yes I didn't manage the `application/www-x-urlencoded` content type.
